#!/bin/bash

# ~/.config/zsh/aliases

# ls
alias ls='ls -GF'
alias l='ls'
alias la='l -A'
alias ll='l -o'
alias lla='l -oA'

# cd
alias ..='cd ..'
alias ...='cd ../..'

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# Git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log --graph --oneline --decorate'
alias gd='git diff'
alias gp='git pull'
alias gpsh='git push'
alias gf='git fetch'
alias gcl='git clone'

alias gl1="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all"
alias gl2="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
