#!/bin/bash

# ~/.config/zsh/aliases

alias j='jobs -l'

alias bh='bat --plain --language help'

# neovim
alias v='nvim'

# tmux
alias t='tmux a || tmux'

# ls
alias l='eza'
alias ls='eza --all --long'
alias la='eza --all'
alias ll='eza --long'
alias lt='eza --tree --git-ignore'

# cd
alias ..='cd ..'
alias ...='cd ../..'

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# Git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gp='git pull'
alias gpsh='git push'
alias gf='git fetch'

alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'"
alias gla='gl --all'
alias glm='git log --pretty=format:%B'

# Conflicts
alias fix='$EDITOR `gd --name-only | uniq`'

# change alacritty theme
alias dark-alacritty='/Users/Ben.Berry-Allwood/.local/bin/alacritty-colorscheme apply nord-dark.yaml'
alias light-alacritty='/Users/Ben.Berry-Allwood/.local/bin/alacritty-colorscheme apply polar-light.yaml'

# change nvim theme
alias dark-nvim="sed -i '' '/vim\.g\.catppuccin_flavour = \".*\"/s/latte/frappe/' /Users/Ben.Berry-Allwood/.config/nvim/lua/user/colorscheme.lua\
  && sed -i '' '/set background/s/light/dark/' /Users/Ben.Berry-Allwood/.config/nvim/lua/user/colorscheme.lua\
  && sed -i '' '/colorscheme/s/dayfox/nordfox/' /Users/Ben.Berry-Allwood/.config/nvim/lua/user/colorscheme.lua"
alias light-nvim="sed -i '' '/vim\.g\.catppuccin_flavour = \".*\"/s/frappe/latte/' /Users/Ben.Berry-Allwood/.config/nvim/lua/user/colorscheme.lua\
  && sed -i '' '/set background/s/dark/light/' /Users/Ben.Berry-Allwood/.config/nvim/lua/user/colorscheme.lua\
  && sed -i '' '/colorscheme/s/nordfox/dayfox/' /Users/Ben.Berry-Allwood/.config/nvim/lua/user/colorscheme.lua"

# change nvim and alacritty theme
alias dark='dark-alacritty && dark-nvim'
alias light='light-alacritty && light-nvim'

# tree
alias tree='lt'
alias tree1='tree --level 1'
alias tree2='tree --level 2'
alias tree3='tree --level 3'
alias tree4='tree --level 4'

# poetry (for python)
alias pi='poetry install --all-extras'
alias pis='pi --sync'
alias psh='poetry shell'

# swap-env
alias e='swap-env'

# databricks-cli
alias dab='databricks bundle'

# mise
alias mr='mise run'
alias mx='mise exec'
