#!/bin/bash

# ~/.config/zsh/aliases

# ls
alias ls='ls -GF'
alias l='ls'
alias la='l -A'
alias ll='l -o'
alias lla='l -oA'

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# Git
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log'
